
# encoding: utf-8

default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5433
  username: railsuser
  password: rails123
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: box_tracker_development

test:
  <<: *default
  database: box_tracker_test

production:
  <<: *default
  database: box_tracker_production
  username: railsuser
  password: <%= ENV["BOX_TRACKER_DATABASE_PASSWORD"] || "rails123" %>
  host: 127.0.0.1
  port: 5433

